//я буду кидать названия задач с литкода а ты давай легкие простые решения
// прописывая консольлоги для разжовывания задачи
const arr = [
    'Find the Maximum Length of Valid Subsequence II',
    'Two Sum',
    'Palindrome Number',
    'Roman to Integer',
    'Longest Common Prefix',
    'Valid Parentheses',
    'Merge Two Sorted Lists',
    'Remove Duplicates from Sorted Array',
    'Remove Element',
    'Find the Index of the First Occurrence in a String',
    'Search Insert Position',
    'Length of Last Word',
    'Plus One',
    'Add Binary',
    'Sqrt(x)',
    'Climbing Stairs',
    'Remove Duplicates from Sorted List',
    'Merge Sorted Array',
    'Binary Tree Inorder Traversal',
    'Same Tree',
    'Symmetric Tree',
    'Maximum Depth of Binary Tree',
    'Convert Sorted Array to Binary Search Tree',
    'Balanced Binary Tree',
    'Minimum Depth of Binary Tree',
    'Path Sum',
    'Pascal`s Triangle',
    'Pascal`s Triangle II',
    'Best Time to Buy and Sell Stock',
    'Valid Palindrome',
    'Single Number',
    'Linked List Cycle',
    'Binary Tree Preorder Traversal',
    'Binary Tree Postorder Traversal',
    'Read N Characters Given Read4',
    'Intersection of Two Linked Lists',
    'Missing Ranges',
    'Excel Sheet Column Title',
    'Majority Element',
    'Two Sum III - Data structure design',
    'Excel Sheet Column Number',
    'Combine Two Tables',
    'Employees Earning More Than Their Managers',
    'Duplicate Emails',
    'Customers Who Never Order',
    'Reverse Bits',
    'Number of 1 Bits',
    'Valid Phone Numbers',
    'Tenth Line',
    'Delete Duplicate Emails',
    'Rising Temperature',
    'Happy Number',
    'Remove Linked List Elements',
    'Isomorphic Strings',
    'Reverse Linked List',
    'Contains Duplicate',
    'Contains Duplicate II',
    'Count Complete Tree Nodes',
    'Implement Stack using Queues',
    'Invert Binary Tree',
    'Summary Ranges',
    'Power of Two',
    'Implement Queue using Stacks',
    'Palindrome Linked List',
    'Valid Anagram',
    'Shortest Word Distance',
    'Strobogrammatic Number',
    'Meeting Rooms',
    'Binary Tree Paths',
    'Add Digits',
    'Ugly Number',
    'Palindrome Permutation',
    'Missing Number',
    'Closest Binary Search Tree Value',
    'First Bad Version',
    'Move Zeroes',
    'Word Pattern',
    'Nim Game',
    'Flip Game',
    'Range Sum Query - Immutable',
    'Power of Three',
    'Counting Bits',
    'Power of Four',
    'Reverse String',
    'Reverse Vowels of a String',
    'Moving Average from Data Stream',
    'Intersection of Two Arrays',
    'Intersection of Two Arrays II',
    'Logger Rate Limiter',
    'Valid Perfect Square',
    'Guess Number Higher or Lower',
    'Ransom Note',
    'First Unique Character in a String',
    'Find the Difference',
    'Is Subsequence',
    'Binary Watch',
    'Sum of Left Leaves',
    'Convert a Number to Hexadecimal',
    'Valid Word Abbreviation',
    'Longest Palindrome',
    'Fizz Buzz',
    'Third Maximum Number',
    'Add Strings',
    'Valid Word Square',
    'Number of Segments in a String',
    'Arranging Coins',
    'Find All Numbers Disappeared in an Array',
    'Assign Cookies',
    'Repeated Substring Pattern',
    'Hamming Distance',
    'Island Perimeter',
    'Number Complement',
    'License Key Formatting',
    'Max Consecutive Ones',
    'Construct the Rectangle',
    'Teemo Attacking',
    'Next Greater Element I',
    'Keyboard Row',
    'Find Mode in Binary Search Tree',
    'Base 7',
    'Relative Ranks',
    'Perfect Number',
    'Fibonacci Number',
    'Game Play Analysis I',
    'Game Play Analysis II',
    'Detect Capital',
    'Longest Uncommon Subsequence I',
    'Minimum Absolute Difference in BST',
    'Reverse String II',
    'Diameter of Binary Tree',
    'Student Attendance Record I',
    'Reverse Words in a String III',
    'Maximum Depth of N-ary Tree',
    'Array Partition',
    'Binary Tree Tilt',
    'Reshape the Matrix',
    'Subtree of Another Tree',
    'Distribute Candies',
    'Employee Bonus',
    'Find Customer Referee',
    'Customer Placing the Largest Number of Orders',
    'N-ary Tree Preorder Traversal',
    'N-ary Tree Postorder Traversal',
    'Longest Harmonious Subsequence',
    'Big Countries',
    'Classes With at Least 5 Students',
    'Friend Requests I: Overall Acceptance Rate',
    'Range Addition II',
    'Minimum Index Sum of Two Lists',
    'Consecutive Available Seats',
    'Design Compressed String Iterator',
    'Can Place Flowers',
    'Sales Person',
    'Triangle Judgement',
    'Shortest Distance in a Line',
    'Merge Two Binary Trees',
    'Biggest Single Number',
    'Not Boring Movies',
    'Swap Salary',
    'Maximum Product of Three Numbers',
    'Average of Levels in Binary Tree',
    'Maximum Average Subarray I',
    'Set Mismatch',
    'Two Sum IV - Input is a BST',
    'Robot Return to Origin',
    'Image Smoother',
    'Second Minimum Node In a Binary Tree',
    'Longest Continuous Increasing Subsequence',
    'Valid Palindrome II',
    'Baseball Game',
    'Binary Number with Alternating Bits',
    'Count Binary Substrings',
    'Degree of an Array',
    'Search in a Binary Search Tree',
    'Kth Largest Element in a Stream',
    'Binary Search',
    'Design HashSet',
    'Design HashMap',
    'To Lower Case',
    '1-bit and 2-bit Characters',
    'Find Pivot Index',
    'Self Dividing Numbers',
    'Flood Fill',
    'Sentence Similarity',
    'Find Smallest Letter Greater Than Target',
    'Min Cost Climbing Stairs',
    'Largest Number At Least Twice of Others',
    'Shortest Completing Word',
    'Find Anagram Mappings',
    'Prime Number of Set Bits in Binary Representation',
    'Toeplitz Matrix',
    'Jewels and Stones',
    'Minimum Distance Between BST Nodes',
    'Rotate String',
    'Similar RGB Color',
    'Unique Morse Code Words',
    'Number of Lines To Write String',
    'Largest Triangle Area',
    'Most Common Word',
    'Shortest Distance to a Character',
    'Goat Latin',
    'Positions of Large Groups',
    'Flipping an Image',
    'Rectangle Overlap',
    'Backspace String Compare',
    'Buddy Strings',
    'Lemonade Change',
    'Transpose Matrix',
    'Binary Gap',
    'Leaf-Similar Trees',
    'Middle of the Linked List',
    'Projection Area of 3D Shapes',
    'Uncommon Words from Two Sentences',
    'Fair Candy Swap',
    'Surface Area of 3D Shapes',
    'Monotonic Array',
    'Increasing Order Search Tree',
    'Sort Array By Parity',
    'Smallest Range I',
    'X of a Kind in a Deck of Cards',
    'Reverse Only Letters',
    'Sort Array By Parity II',
    'Long Pressed Name',
    'Unique Email Addresses',
    'Number of Recent Calls',
    'Range Sum of BST',
    'Valid Mountain Array',
    'DI String Match',
    'Delete Columns to Make Sorted',
    'Verifying an Alien Dictionary',
    'N-Repeated Element in Size 2N Array',
    'Univalued Binary Tree',
    'Largest Perimeter Triangle',
    'Squares of a Sorted Array',
    'Add to Array-Form of Integer',
    'Cousins in Binary Tree',
    'Find the Town Judge',
    'Available Captures for Rook',
    'Find Common Characters',
    'Maximize Sum Of Array After K Negations',
    'Complement of Base 10 Integer',
    'Partition Array Into Three Parts With Equal Sum',
    'Binary Prefix Divisible By 5',
    'Remove Outermost Parentheses',
    'Sum of Root To Leaf Binary Numbers',
    'Divisor Game',
    'Matrix Cells in Distance Order',
    'Valid Boomerang',
    'Last Stone Weight',
    'Remove All Adjacent Duplicates In String',
    'Actors and Directors Who Cooperated At Least Three Times',
    'Height Checker',
    'Confusing Number',
    'Fixed Point',
    'Index Pairs of a String',
    'Product Sales Analysis I',
    'Product Sales Analysis II',
    'Greatest Common Divisor of Strings',
    'Project Employees I',
    'Project Employees II',
    'Occurrences After Bigram',
    'Sales Analysis I',
    'Sales Analysis II',
    'Sales Analysis III',
    'Sum of Digits in the Minimum Number',
    'High Five',
    'Duplicate Zeros',
    'Two Sum Less Than K',
    'Distribute Candies to People',
    'Defanging an IP Address',
    'Reported Posts',
    'Print in Order',
    'Number of Days in a Month',
    'Remove Vowels from a String',
    'Relative Sort Array',
    'Number of Equivalent Domino Pairs',
    'Largest Unique Number',
    'Armstrong Number',
    'N-th Tribonacci Number',
    'User Activity for the Past 30 Days I',
    'User Activity for the Past 30 Days II',
    'Article Views I',
    'Check If a Number Is Majority Element in a Sorted Array',
    'Day of the Year',
    'Find Words That Can Be Formed by Characters',
    'Single-Row Keyboard',
    'Immediate Food Delivery I',
    'Prime Arrangements',
    'Diet Plan Performance',
    'Reformat Department Table',
    'Count Substrings with Only One Distinct Letter',
    'Distance Between Bus Stops',
    'Day of the Week',
    'Maximum Number of Balloons',
    'How Many Apples Can You Put into the Basket',
    'Minimum Absolute Difference',
    'Unique Number of Occurrences',
    'Queries Quality and Percentage',
    'Intersection of Three Sorted Arrays',
    'Minimum Cost to Move Chips to The Same Position',
    'Split a String in Balanced Strings',
    'Missing Number In Arithmetic Progression',
    'Check If It Is a Straight Line',
    'Number of Comments per Post',
    'Array Transformation',
    'Average Selling Price',
    'Cells with Odd Values in a Matrix',
    'Shift 2D Grid',
    'Minimum Time Visiting All Points',
    'Hexspeak',
    'Find Winner on a Tic Tac Toe Game',
    'Traffic Light Controlled Intersection',
    'Students and Examinations',
    'Subtract the Product and Sum of Digits of an Integer',
    'Element `ppearing , Array',
    'Convert Binary Number in a Linked List to Integer',
    'Weather Type in Each Country',
    'Find Numbers with Even Number of Digits',
    'Replace Elements with Greatest Element on Right Side',
    'Find the Team Size',
    'Find N Unique Integers Sum up to Zero',
    'Decrypt String from Alphabet to Integer Mapping',
    'Decompress Run-Length Encoded List',
    'Convert Integer to the Sum of Two No-Zero Integers',
    'Ads Performance',
    'Maximum 69 Number',
    'List the Products Ordered in a Period',
    'Rank Transform of an Array',
    'Remove Palindromic Subsequences',
    'The K Weakest Rows in a Matrix',
    'Number of Steps to Reduce a Number to Zero',
    'Check If N and Its Double Exist',
    'Students With Invalid Departments',
    'Count Negative Numbers in a Sorted Matrix',
    'Sort Integers by The Number of 1 Bits',
    'Number of Days Between Two Dates',
    'How Many Numbers Are Smaller Than the Current Number',
    'Increasing Decreasing String',
    'Generate a String With Characters That Have Odd Counts',
    'Replace Employee ID With The Unique Identifier',
    'Find a Corresponding Node of a Binary Tree in a Clone of That Tree',
    'Lucky Numbers in a Matrix',
    'Find the Distance Value Between Two Arrays',
    'Create Target Array in the Given Order',
    'Find Lucky Integer in an Array',
    'Count Largest Group',
    'Minimum Subsequence in Non-Increasing Order',
    'Top Travellers',
    'String Matching in an Array',
    'Minimum Value to Get Positive Step by Step Sum',
    'Reformat The String',
    'NPV Queries',
    'Maximum Score After Splitting a String',
    'Counting Elements',
    'Perform String Shifts',
    'Kids With the Greatest Number of Candies',
    'Create a Session Bar Chart',
    'Destination City',
    'Check If All 1`s Are at Least Length K Places Away',
    'Consecutive Characters',
    'Number of Students Doing Homework at a Given Time',
    'Check If a Word Occurs As a Prefix of Any Word in a Sentence',
    'Make Two Arrays Equal by Reversing Subarrays',
    'Maximum Product of Two Elements in an Array',
    'Find All The Lonely Nodes',
    'Shuffle the Array',
    'Delete N Nodes After M Nodes of a Linked List',
    'Final Prices With a Special Discount in a Shop',
    'Running Sum of 1d Array',
    'Group Sold Products By The Date',
    'XOR Operation in an Array',
    'Average Salary Excluding the Minimum and Maximum Salary',
    'Friendly Movies Streamed Last Month',
    'Path Crossing',
    'Can Make Arithmetic Progression From Sequence',
    'Reformat Date',
    'Customer Order Frequency',
    'Number of Good Pairs',
    'Find Users With Valid E-Mails',
    'Water Bottles',
    'Count Odd Numbers in an Interval Range',
    'Patients With a Condition',
    'Shuffle String',
    'Count Good Triplets',
    'Kth Missing Positive Number',
    'Fix Product Name Format',
    'Make The String Great',
    'Three Consecutive Odds',
    'Thousand Separator',
    'Most Visited Sector in a Circular Track',
    'Unique Orders and Customers Per Month',
    'Detect Pattern of Length M Repeated K or More Times',
    'Warehouse Manager',
    'Matrix Diagonal Sum',
    'Replace All ?`s to Avoid Consecutive Repeating Characters',
    'Customer Who Visited but Did Not Make Any Transactions',
    'Special Positions in a Binary Matrix',
    'Bank Account Summary II',
    'Sum of All Odd Length Subarrays',
    'Rearrange Spaces Between Words',
    'Crawler Log Folder',
    'Design Parking System',
    'Sellers With No Sales',
    'Special Array With X Elements Greater Than or Equal X',
    'Maximum Nesting Depth of the Parentheses',
    'Mean of Array After Removing Some Elements',
    'All Valid Triplets That Can Represent a Country',
    'Largest Substring Between Two Equal Characters',
    'Slowest Key',
    'Percentage of Users Attended a Contest',
    'Sort Array by Increasing Frequency',
    'Widest Vertical Area Between Two Points Containing No Points',
    'Check Array Formation Through Concatenation',
    'Get Maximum in Generated Array',
    'Defuse the Bomb',
    'Design an Ordered Stream',
    'Average Time of Process per Machine',
    'Check If Two String Arrays are Equivalent',
    'Fix Names in a Table',
    'Maximum Repeating Substring',
    'Richest Customer Wealth',
    'Product`s Worth Over Invoices',
    'Goal Parser Interpretation',
    'Invalid Tweets',
    'Count the Number of Consistent Strings',
    'Count of Matches in Tournament',
    'Daily Leads and Partners',
    'Reformat Phone Number',
    'Number of Students Unable to Eat Lunch',
    'Determine if String Halves Are Alike',
    'Largest Subarray Length K',
    'Maximum Units on a Truck',
    'Calculate Money in Leetcode Bank',
    'Decode XORed Array',
    'Number Of Rectangles That Can Form The Largest Square',
    'Find Followers Count',
    'The Number of Employees Which Report to Each Employee',
    'Find the Highest Altitude',
    'Latest Time by Replacing Hidden Digits',
    'Find Total Time Spent by Each Employee',
    'Maximum Number of Balls in a Box',
    'Sum of Unique Elements',
    'Check if Array Is Sorted and Rotated',
    'Recyclable and Low Fat Products',
    'Minimum Changes To Make Alternating Binary String',
    'Longest Nice Substring',
    'Merge Strings Alternately',
    'Count Items Matching a Rule',
    'Product`s Price for Each Store',
    'Find Nearest Point That Has the Same X or Y Coordinate',
    'Check if Binary String Has at Most One Segment of Ones',
    'Primary Department for Each Employee',
    'Check if One String Swap Can Make Strings Equal',
    'Find Center of Star Graph',
    'Rearrange Products Table',
    'Second Largest Digit in a String',
    'Maximum Ascending Subarray Sum',
    'Number of Different Integers in a String',
    'Ad-Free Sessions',
    'Determine Color of a Chessboard Square',
    'Truncate Sentence',
    'Find Customers With Positive Revenue this Year',
    'Sign of the Product of an Array',
    'Faulty Sensor',
    'Minimum Operations to Make the Array Increasing',
    'Check if the Sentence Is Pangram',
    'Sum of Digits in Base K',
    'Replace All Digits with Characters',
    'Minimum Distance to the Target Element',
    'Convert Date Format',
    'Maximum Population Year',
    'Sorting the Sentence',
    'Sum of All Subset XOR Totals',
    'Longer Contiguous Segments of Ones than Zeros',
    'Calculate Special Bonus',
    'Substrings of Size Three with Distinct Characters',
    'Check if Word Equals Summation of Two Words',
    'Determine Whether Matrix Can Be Obtained By Rotation',
    'The Latest Login in 2020',
    'Check if All the Integers in a Range Are Covered',
    'Redistribute Characters to Make All Strings Equal',
    'Largest Odd Number in String',
    'Remove One Element to Make the Array Strictly Increasing',
    'Maximum Product Difference Between Two Pairs',
    'Build Array from Permutation',
    'Count Square Sum Triples',
    'Concatenation of Array',
    'Check if String Is Decomposable Into Value-Equal Substrings',
    'Maximum Number of Words You Can Type',
    'Users That Actively Request Confirmation Messages',
    'Check if All Characters Have Equal Number of Occurrences',
    'Sum of Digits of String After Convert',
    'Three Divisors',
    'Delete Characters to Make Fancy String',
    'Check If String Is a Prefix of Array',
    'Employees With Missing Information',
    'Number of Strings That Appear as Substrings in Word',
    'Find if Path Exists in Graph',
    'Minimum Time to Type Word Using Special Typewriter',
    'Employees Whose Manager Left the Company',
    'Find Greatest Common Divisor of Array',
    'Minimum Difference Between Highest and Lowest of K Scores',
    'Find the Middle Index in Array',
    'Count Special Quadruplets',
    'Reverse Prefix of Word',
    'Count Number of Pairs With Absolute Difference K',
    'Final Value of Variable After Performing Operations',
    'Maximum Difference Between Increasing Elements',
    'Convert 1D Array Into 2D Array',
    'Low-Quality Problems',
    'Minimum Moves to Convert String',
    'Two Out of Three',
    'Minimum Number of Moves to Seat Everyone',
    'Check if Numbers Are Ascending in a Sentence',
    'Number of Valid Words in a Sentence',
    'Kth Distinct String in an Array',
    'Smallest Index With Equal Value',
    'Count Vowel Substrings of a String',
    'Check Whether Two Strings are Almost Equivalent',
    'The Winner University',
    'Time Needed to Buy Tickets',
    'Two Furthest Houses With Different Colors',
    'The Number of Rich Customers',
    'Count Common Words With One Occurrence',
    'Find Target Indices After Sorting Array',
    'Finding 3-Digit Even Numbers',
    'Find Subsequence of Length K With the Largest Sum',
    'Rings and Rods',
    'Find First Palindromic String in the Array',
    'Maximum Number of Words Found in Sentences',
    'A Number After a Double Reversal',
    'Check if All A`s Appears Before All B',
    'Capitalize the Title',
    'Check if Every Row and Column Contains All Numbers',
    'Divide a String Into Groups of Size k',
    'Minimum Cost of Buying Candies With Discount',
    'Count Elements With Strictly Smaller and Greater Elements',
    'Keep Multiplying Found Values by Two',
    'Minimum Sum of Four Digit Number After Splitting Digits',
    'Sort Even and Odd Indices Independently',
    'Count Operations to Obtain Zero',
    'Count Equal and Divisible Pairs in an Array',
    'Count Integers With Even Digit Sum',
    'Counting Words With a Given Prefix',
    'Most Frequent Number Following Key In an Array',
    'Cells in a Range on an Excel Sheet',
    'Find All K-Distant Indices in an Array',
    'The Number of Users That Are Eligible for Discount',
    'Divide Array Into Equal Pairs',
    'Count Hills and Valleys in an Array',
    'Find the Difference of Two Arrays',
    'Minimum Bit Flips to Convert Number',
    'Minimum Number of Operations to Convert Time',
    'Check if an Array Is Consecutive',
    'The Users That Are Eligible for Discount',
    'Largest Number After Digit Swaps by Parity',
    'Add Two Integers',
    'Root Equals Sum of Children',
    'Find Closest Number to Zero',
    'Calculate Digit Sum of a String',
    'Intersection of Multiple Arrays',
    'Count Prefixes of a Given String',
    'Remove Digit From Number to Maximize Result',
    'Largest 3-Same-Digit Number in String',
    'Find the K-Beauty of a Number',
    'Find Resultant Array After Removing Anagrams',
    'Percentage of Letter in String',
    'Check if Number Has Equal Digit Count and Digit Value',
    'Rearrange Characters to Make Target String',
    'Min Max Game',
    'Strong Password Checker II',
    'Calculate Amount Paid in Taxes',
    'Greatest English Letter in Upper and Lower Case',
    'Count Asterisks',
    'Check if Matrix Is X-Matrix',
    'Decode the Message',
    'Product Sales Analysis V',
    'Evaluate Boolean Binary Tree',
    'Minimum Amount of Time to Fill Cups',
    'All the Matches of the League',
    'Maximum Number of Pairs in Array',
    'Best Poker Hand',
    'First Letter to Appear Twice',
    'Number of Unique Subjects Taught by Each Teacher',
    'Make Array Zero by Subtracting Equal Amounts',
    'Merge Similar Items',
    'Number of Arithmetic Triplets',
    'Largest Local Values in a Matrix',
    'Sort the Olympic Table',
    'Minimum Recolors to Get K Consecutive Black Blocks',
    'Minimum Hours of Training to Win a Competition',
    'Longest Subsequence With Limited Sum',
    'Find Subarrays With Equal Sum',
    'Check Distances Between Same Letters',
    'Most Frequent Even Element',
    'Count Days Spent Together',
    'Smallest Even Multiple',
    'Sort the People',
    'Remove Letter To Equalize Frequency',
    'Number of Common Factors',
    'The Employee That Worked on the Longest Task',
    'Number of Valid Clock Times',
    'Largest Positive Integer That Exists With Its Negative',
    'Determine if Two Events Have Conflict',
    'Odd String Difference',
    'Average Value of Even Numbers That Are Divisible by Three',
    'Apply Operations to an Array',
    'Number of Distinct Averages',
    'Convert the Temperature',
    'Number of Unequal Triplets in Array',
    'Form a Chemical Bond',
    'Minimum Cuts to Divide a Circle',
    'Find the Pivot Integer',
    'Circular Sentence',
    'Maximum Value of a String in an Array',
    'Delete Greatest Value in Each Row',
    'Concatenate the Name and the Profession',
    'Count Pairs Of Similar Strings',
    'Maximum Enemy Forts That Can Be Captured',
    'Shortest Distance to Target String in a Circular Array',
    'Count the Digits That Divide a Number',
    'Categorize Box According to Criteria',
    'Maximum Count of Positive Integer and Negative Integer',
    'Difference Between Element Sum and Digit Sum of an Array',
    'Minimum Common Value',
    'Alternating Digit Sum',
    'Count Distinct Numbers on Board',
    'Separate the Digits in an Array',
    'Take Gifts From the Richest Pile',
    'Find the Array Concatenation Value',
    'Maximum Difference by Remapping a Digit',
    'Merge Two 2D Arrays by Summing Values',
    'Left and Right Sum Differences',
    'Split With Minimum Sum',
    'Pass the Pillow',
    'Count the Number of Vowel Strings in Range',
    'Distribute Money to Maximum Children',
    'Number of Even and Odd Bits',
    'K Items With the Maximum Sum',
    'Form Smallest Number From Two Digit Arrays',
    'Find the Longest Balanced Substring of a Binary String',
    'Prime In Diagonal',
    'Array Prototype Last',
    'Counter',
    'Sleep',
    'Array Reduce Transformation',
    'Function Composition',
    'Filter Elements from Array',
    'Apply Transform Over Each Element in Array',
    'Find the Width of Columns of a Grid',
    'Row With Maximum Ones',
    'Find the Maximum Divisibility Score',
    'Generate Fibonacci Sequence',
    'Calculate Delayed Arrival Time',
    'Sum Multiples',
    'Maximum Sum With Exactly K Elements',
    'Determine the Winner of a Bowling Game',
    'Counter II',
    'Allow One Function Call',
    'Create Hello World Function',
    'Find Latest Salaries',
    'Count Artist Occurrences On Spotify Ranking List',
    'Find the Distinct Difference Array',
    'Chunk Array',
    'Number of Senior Citizens',
    'Find the Losers of the Circular Game',
    'Bikes Last Time Used',
    'Extract Kth Character From The Rope Tree',
    'Infinite Method Object',
    'Array Wrapper',
    'Minimum String Length After Removing Substrings',
    'Lexicographically Smallest Palindrome',
    'Return Length of Arguments Passed',
    'To Be Or Not To Be',
    'Buy Two Chocolates',
    'Remove Trailing Zeros From a String',
    'Timeout Cancellation',
    'Minimize String Length',
    'Semi-Ordered Permutation',
    'Add Two Promises',
    'Sort By',
    'Interval Cancellation',
    'Calculator with Method Chaining',
    'Is Object Empty',
    'Count Houses in a Circular Street',
    'Check if The Number is Fascinating',
    'Neither Minimum nor Maximum',
    'Total Distance Traveled',
    'Find Maximum Number of String Pairs',
    'Number of Beautiful Pairs',
    'Next Day',
    'Longest Even Odd Subarray With Threshold',
    'Longest Alternating Subarray',
    'Find the Maximum Achievable Number',
    'Array Upper Bound',
    'Sum of Squares of Special Elements',
    'Check if Array is Good',
    'Split Strings by Separator',
    'Create Object from Two Arrays',
    'Repeat String',
    'Partial Function with Placeholders',
    'Number of Employees Who Met the Target',
    'Factorial Generator',
    'Array Prototype ForEach',
    'Account Balance After Rounded Purchase',
    'Faulty Keyboard',
    'Max Pair Sum in an Array',
    'Inversion of Object',
    'Count Pairs Whose Sum is Less than Target',
    'Check if a String Is an Acronym of Words',
    'Furthest Point From Origin',
    'Total Traveled Distance',
    'Check if Strings Can be Made Equal With Operations I',
    'Count Symmetric Integers',
    'Points That Intersect With Cars',
    'Highest Salaries Difference',
    'Minimum Right Shifts to Sort the Array',
    'Sum of Values at Indices With K Set Bits',
    'Maximum Odd Binary Number',
    'Minimum Operations to Collect Elements',
    'Maximum Value of an Ordered Triplet I',
    'Create a DataFrame from List',
    'Get the Size of a DataFrame',
    'Display the First Three Rows',
    'Select Data',
    'Create a New Column',
    'Drop Duplicate Rows',
    'Drop Missing Data',
    'Modify Columns',
    'Rename Columns',
    'Change Data Type',
    'Fill Missing Data',
    'Reshape Data: Concatenate',
    'Reshape Data: Pivot',
    'Reshape Data: Melt',
    'Method Chaining',
    'Divisible and Non-divisible Sums Difference',
    'Last Visited Integers',
    'Longest Unequal Adjacent Groups Subsequence I',
    'Find Indices With Index and Value Difference I',
    'Minimum Sum of Mountain Triplets I',
    'Subarrays Distinct Element Sum of Squares I',
    'Find the K-or of an Array',
    'Find Champion I',
    'Distribute Candies Among Children I',
    'Maximum Strong Pair XOR I',
    'Make Three Strings Equal',
    'Find Words Containing Character',
    'Matrix Similarity After Cyclic Shifts',
    'Find the Peaks',
    'Find Common Elements Between Two Arrays',
    'Count Tested Devices After Test Operations',
    'Find Missing and Repeated Values',
    'Count the Number of Incremovable Subarrays I',
    'Minimum Number Game',
    'Check if Bitwise OR Has Trailing Zeros',
    'Calculate Compressed Mean',
    'Find Expensive Cities',
    'Loan Types',
    'Smallest Missing Integer Greater Than Sequential Prefix Sum',
    'Maximum Area of Longest Diagonal Rectangle',
    'Count Elements With Maximum Frequency',
    'Divide an Array Into Subarrays With Minimum Cost I',
    'Minimum Number of Pushes to Type Word I',
    'Number of Changing Keys',
    'Type of Triangle',
    'Ant on the Boundary',
    'Count Numbers With Unique Digits II',
    'Modify the Matrix',
    'Maximum Number of Operations With the Same Score I',
    'Count Prefix and Suffix Pairs I',
    'Split the Array',
    'Find Candidates for Data Scientist Position',
    'Classifying Triangles by Lengths',
    'Find All Unique Email Domains',
    'Winner of the Linked List Game',
    'Linked List Frequency',
    'Minimum Operations to Exceed Threshold Value I',
    'Distribute Elements Into Two Arrays I',
    'Apple Redistribution into Boxes',
    'Find the Sum of Encrypted Integers',
    'Existence of a Substring in a String and Its Reverse',
    'Maximum Length Substring With Two Occurrences',
    'Shortest Subarray With OR at Least K I',
    'Harshad Number',
    'Longest Strictly Increasing or Strictly Decreasing Subarray',
    'Score of a String',
    'Latest Time You Can Obtain After Replacing Characters',
    'Count the Number of Special Characters I',
    'Make a Square with the Same Color',
    'Find the Integer Added to Array I',
    'Valid Word',
    'Check if Grid Satisfies Conditions',
    'Permutation Difference between Two Strings',
    'Invalid Tweets II',
    'Special Array I',
    'Find the XOR of Numbers Which Appear Twice',
    'Find the Number of Good Pairs I',
    'Minimum Number of Chairs in a Waiting Room',
    'Second Day Verification',
    'Bitwise OR of Adjacent Elements',
    'Clear Digits',
    'Find the Child Who Has the Ball After K Seconds',
    'Count Pairs That Form a Complete Day I',
    'Find Minimum Operations to Make All Elements Divisible by Three',
    'Minimum Average of Smallest and Largest Elements',
    'Find Cities in Each State',
    'Count Triplets with Even XOR Set Bits I',
    'Maximum Height of a Triangle',
    'Alternating Groups I',
    'Find the Encrypted String',
    'Lexicographically Smallest String After a Swap',
    'Find the Winning Player in Coin Game',
    'Number of Bit Changes to Make Two Integers Equal',
    'Find if Digit Game Can Be Won',
    'Find the Number of Winning Players',
    'Design Neighbor Sum Service',
    'Premier League Table Ranking',
    'Snake in Matrix',
    'Count Substrings That Satisfy K-Constraint I',
    'Convert Doubly Linked List to Array I',
    'Final Array State After K Multiplication Operations I',
    'Find the Key of the Numbers',
    'Check if Two Chessboard Squares Have the Same Color',
    'Convert Date to Binary',
    'Find Indices of Stable Mountains',
    'The Two Sneaky Numbers of Digitville',
    'Minimum Element After Replacement With Digit Sum',
    'Find the K-th Character in String Game I',
    'Construct the Minimum Bitwise Array I',
    'Find X-Sum of All K-Long Subarrays I',
    'Find the Original Typed String I',
    'Check Balanced String',
    'Smallest Divisible Digit Product I',
    'Adjacent Increasing Subarrays Detection I',
    'Minimum Total Operations',
    'Make Array Elements Equal to Zero',
    'Books with NULL Ratings',
    'Stone Removal Game',
    'Minimum Positive Sum Subarray',
    'Smallest Number With All Set Bits',
    'Minimum Operations to Make Array Values Equal to K',
    'Transformed Array',
    'Button with Longest Push Time',
    'Count Subarrays of Length Three With a Condition',
    'Minimum Number of Operations to Make Elements in Array Distinct',
    'Minimum Operations to Make Columns Strictly Increasing',
    'Substring Matching Pattern',
    'Maximum Subarray With Equal Products',
    'Find Products with Three Consecutive Digits',
    'Zigzag Grid Traversal With Skip',
    'Maximum Difference Between Adjacent Elements in a Circular Array',
    'Sum of Variable Length Subarrays',
    'Count Partitions with Even Sum Difference',
    'Find Valid Emails',
    'Find Valid Pair of Adjacent Digits in String',
    'Maximum Difference Between Even and Odd Frequency I',
    'Maximum Students on a Single Bench',
    'Sum of Good Numbers',
    'Find Special Substring of Length K',
    'Check If Digits Are Equal in String After Operations I',
    'Find Products with Valid Serial Numbers',
    'Transform Array by Parity',
    'Find the Largest Almost Missing Integer',
    'Fruits Into Baskets II',
    'Unique 3-Digit Even Numbers',
    'Maximum Unique Subarray Sum After Deletion',
    'Phone Number Prefix',
    'Maximum Containers on a Ship',
    'Reverse Degree of a String',
    'Minimum Cost to Reach Every Position',
    'Minimum Pair Removal to Sort Array I',
    'Minimum Operations to Make Array Sum Divisible by K',
    'Find Closest Person',
    'Maximum Product of Two Digits',
    'Find Most Frequent Vowel and Consonant',
    'Minimum Deletions for At Most K Distinct Characters',
    'Smallest Index With Digit Sum Equal to Index',
    'Find Minimum Log Transportation Cost',
    'Find Books with No Available Copies',
    'Find the Shortest Superstring II',
    'Count Odd Letters from Number',
    'Generate Tag for Video Caption',
    'Check if Any Element Has Prime Frequency',
    'Hexadecimal and Hexatrigesimal Conversion', 'Coupon Code Validator', 'Add Two Numbers',
    'Longest Substring Without Repeating Characters',
    'Longest Palindromic Substring',
    'Zigzag Conversion',
    'Reverse Integer',
    'String to Integer (atoi)',
    'Container With Most Water',
    'Integer to Roman',
    '3Sum',
    '3Sum Closest',
    'Letter Combinations of a Phone Number',
    '4Sum',
    'Remove Nth Node From End of List',
    'Generate Parentheses',
    'Swap Nodes in Pairs',
    'Divide Two Integers',
    'Next Permutation',
    'Search in Rotated Sorted Array',
    'Find First and Last Position of Element in Sorted Array',
    'Valid Sudoku',
    'Count and Say',
    'Combination Sum',
    'Combination Sum II',
    'Multiply Strings',
    'Jump Game II',
    'Permutations',
    'Permutations II',
    'Rotate Image',
    'Group Anagrams',   'Pow(n)',
    'Maximum Subarray',
    'Spiral Matrix',
    'Jump Game',
    'Merge Intervals',
    'Insert Interval',
    'Spiral Matrix II',
    'Rotate List',
    'Unique Paths',
    'Unique Paths II',
    'Minimum Path Sum',
    'Simplify Path',
    'Edit Distance',
    'Set Matrix Zeroes',
    'Search a 2D Matrix',
    'Sort Colors',
    'Combinations',
    'Subsets',
    'Word Search',
    'Remove Duplicates from Sorted Array II',
    'Search in Rotated Sorted Array II',
    'Remove Duplicates from Sorted List II',
    'Partition List',
    'Gray Code',
    'Subsets II',
    'Decode Ways',
    'Reverse Linked List II',
    'Restore IP Addresses']
console.log(arr.length)
